//! Common utilities shared across L2 tests.

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;

/// Returns the workspace root directory.
/// Uses CARGO_MANIFEST_DIR (which points to test/) and goes up one level.
pub fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

/// Reads environment variables from the .env file generated by the deployer.
/// Skips variables that are already set in the environment.
pub fn read_env_file_by_config() {
    let env_file_path = workspace_root().join("cmd/.env");
    let Ok(env_file) = File::open(env_file_path) else {
        println!(".env file not found, skipping");
        return;
    };

    let reader = BufReader::new(env_file);

    for line in reader.lines() {
        let line = line.expect("Failed to read line");
        if line.starts_with('#') {
            // Skip comments
            continue;
        };
        match line.split_once('=') {
            Some((key, value)) => {
                if std::env::vars().any(|(k, _)| k == key) {
                    continue;
                }
                unsafe { std::env::set_var(key, value) }
            }
            None => continue,
        };
    }
}
